spring:
    profiles:
        active: dev # options: prod，dev，test
    application:
        name: cloud-learning-community-oss-service
    servlet:
        multipart:
            max-file-size: 2048MB
            max-request-size: 2048MB

mybatis-plus:
    global-config:
        field-strategy: 2
        db-column-underline: true
        refresh-mapper: true
        db-config:
            id-type: auto
            table-prefix: t_
    configuration:
        map-underscore-to-camel-case: true
        cache-enabled: false
        return-instance-for-empty-row: true

logback:
    log-dir: /app/oss/service/log

aliyun:
    access-key: LTAI5tKn6G4NfdSVLSqBWP6o13I
    access-secret: s9fBca63Ll5aMhHaCm5wvk2XxZjwxz39lsCs
    point: http://oss-cn-guangzhou.aliyuncs.com
    bucket-name: yjs-learning
    visit-path: https://yjs-learning.oss-cn-guangzhou.aliyuncs.com/

server:
    port: 5508
    servlet:
        context-path: /oss

gateway:
    service:
        url: http://localhost:5500

# 本地保存文件文件夹
local:
    file-dir: /Users/mac/Desktop/j
