spring:
    datasource:
        driver-class-name: com.mysql.cj.jdbc.Driver
        url: jdbc:mysql://172.16.11.6:4806/cloud_learning_community_user_center?useUnicode=true&characterEncoding=utf-8&allowMultiQueries=true&serverTimezone=UTC
        username: joly
        password: joly521
    liquibase:
        change-log: classpath:/db/sql/change.sql
    main:
        allow-bean-definition-overriding: true
